name: godot-ci build web and publish to github pages

on: push

env:
  GODOT_VERSION: 3.5.1
  EXPORT_NAME: ggez
  GITHUB_TOKEN: ${{ github.token }}
  
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  export:
    name: Export
    runs-on: ubuntu-latest
    container:
      image: docker://barichello/godot-ci:3.5.1
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
      - name: Build
        run: |
          sh Tools/optimize_assets.sh
          mkdir -v -p build/web
          godot -v --no-window --export "HTML5" build/web/index.html
          mkdir -v -p build/linux
          godot -v --no-window --export "Linux/X11" build/linux/$EXPORT_NAME.x86_64
          mkdir -v -p build/mac
          godot -v --no-window --export "Mac OSX" build/mac/$EXPORT_NAME.zip
          mkdir -v -p build/windows
          godot -v --no-window --export "Windows Desktop" build/windows/$EXPORT_NAME.exe
          cp strona.html ./build/index.html
      - name: Upload gh pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./build
          
  deploy-to-gh-pages:
    needs: export
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
